# Generated by Django 4.2.30 on 2026-04-20 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_text', models.TextField(verbose_name='Текст конфигурации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Автоматический')),
                ('config_hash', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='devices.device')),
            ],
            options={
                'verbose_name': 'Бэкап конфигурации',
                'verbose_name_plural': 'Бэкапы конфигураций',
                'ordering': ['-created_at'],
            },
        ),
    ]
