# Generated by Django 4.2.30 on 2026-04-20 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя устройства')),
                ('device_type', models.CharField(choices=[('mikrotik_router', 'MikroTik Router'), ('mikrotik_switch', 'MikroTik Switch'), ('linux', 'Linux Server')], max_length=20, verbose_name='Тип')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес управления')),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Расположение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='Статус')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последний ответ')),
                ('uptime', models.CharField(blank=True, max_length=100, verbose_name='Uptime')),
                ('os_version', models.CharField(blank=True, max_length=200, verbose_name='Версия ОС')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Команда')),
                ('output', models.TextField(verbose_name='Результат')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='devices.device')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог команды',
                'verbose_name_plural': 'Лог команд',
                'ordering': ['-executed_at'],
            },
        ),
    ]
